name: Validate Protocol Buffers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-protos:
    runs-on: ubuntu-latest

    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
      
      # Run breaking change detection against the last commit
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/joshcarp/proto-examples.git#branch=main,ref=HEAD~1'
